### ISSUE TITLE
Accepting a react FC as a CustomComponent encourages declaring a react component inside another

### ISSUE THREAD

**Issue by vazhin** [dashty94/mui-rhf-library#10]
## Problem
The problem is that when you want to pass some props down to the custom component, you have to declare a component to be able to accept the props outside, and that causes issues as such:
- React doesn't know what has changed inside that custom component because whenever it sees it. It recreates it again on each parent re-render, that makes it impossible to detect changes.
- It's very expensive to re-create that custom component each time parent renders.

### Problematic Example
```js
{
  name: "values",
  fieldType: 'custom',
  label: t('model.attributes.payable.values.label'),
  CustomComponent: () => <ValuesInValuesField currentValue={currentValue} values={values} />,
  gridProps: { xs: 12 }
}
```

### The desired usage
```js
{
  name: "values",
  fieldType: 'custom',
  label: t('model.attributes.payable.values.label'),
  CustomComponent: <ValuesInValuesField currentValue={currentValue} values={values} />,
  gridProps: { xs: 12 }
}
```

## Solution
Accept a React node for `CustomComponent` instead of a react component:
```js
export type CustomComponentControllerProps = MuiRhfFieldProps & {
    CustomComponent: React.ReactNode;
};
```

**Comment by Revan99** [comment]
> ## Problem
> The problem is that when you want to pass some props down to the custom component, you have to declare a component to be able to accept the props outside, and that causes issues as such:
> 
> * React doesn't know what has changed inside that custom component because whenever it sees it. It recreates it again on each parent re-render, that makes it impossible to detect changes.
> * It's very expensive to re-create that custom component each time parent renders.
> 
> ### Problematic Example
> ```js
> {
>   name: "values",
>   fieldType: 'custom',
>   label: t('model.attributes.payable.values.label'),
>   CustomComponent: () => <ValuesInValuesField currentValue={currentValue} values={values} />,
>   gridProps: { xs: 12 }
> }
> ```
> 
> ### The desired usage
> ```js
> {
>   name: "values",
>   fieldType: 'custom',
>   label: t('model.attributes.payable.values.label'),
>   CustomComponent: <ValuesInValuesField currentValue={currentValue} values={values} />,
>   gridProps: { xs: 12 }
> }
> ```
> 
> ## Solution
> Accept a React node for `CustomComponent` instead of a react component:
> 
> ```js
> export type CustomComponentControllerProps = MuiRhfFieldProps & {
>     CustomComponent: React.ReactNode;
> };
> ```

you can  create your component separately and pass its reference to CustomComponent Attribute 

example:
```
const MyCustomComponent = (props) => {
  return (
    // your input jsx should here and it should be wrapped with Controller component from react-hook-form
  )
}


{
   name: "values",
   fieldType: 'custom',
   label: t('model.attributes.payable.values.label'),
   CustomComponent: MyCustomComponent ,
   gridProps: { xs: 12 },
   props:{
     // you can add anything here and will be passed to your custom component as props
   } 
}
```
